### PR TITLE
Add alma9-jupyterlab user image docs

### PR DESCRIPTION
**Pull request by etejedor**
Initial docs to guide the users with the new alma9 image.

### CODE REVIEW

**Review by diocas — APPROVED** [review]
Seems well explained and to the point. Should we also promise other integrations (hpc)?

Also, we could directly ask for feedback and suggestions of Lab features/extensions that users would like to see. Maybe we should even add a banner in the Lab UI (maybe when the intro banner is migrated to the lab).

What else changes we should document? I can only remember the unavailability of .local modules in the kernels.

**Comment by diocas** [comment]
Also, we no longer have SWAN Projects...

**Review by PMax5 — APPROVED** [review]

**Comment by etejedor** [comment]
> Also, we no longer have SWAN Projects...

On this regard, I say: `- The JupyterLab UI gives more flexibility regarding the location of notebooks. While the classic UI enforces the creation of Projects, which contain notebooks and other files, JupyterLab users can work with any folder in their CERNBox.
`

**Comment by etejedor** [comment]
> Should we also promise other integrations (hpc)?

Perhaps not necessary at this point?

> We could directly ask for feedback and suggestions of Lab features/extensions that users would like to see

Or we allow that users to install their own extensions, what obstacle did we have here?

> What else changes we should document? I can only remember the unavailability of .local modules in the kernels.

I can add this,

**Comment by etejedor** [comment]
Although: currently the behaviour in the terminal and in the notebook is not the same wrt the .local. So I will not add anything until we make the terminal behave the same as the notebook for consistency.

**Comment by diocas** [comment]
Sorry, I skipped that line for some reason...

> Or we allow that users to install their own extensions, what obstacle did we have here?

We never tried. I hope is possible. But we still want to provide some nice defaults.

**Comment by etejedor** [comment]
> We never tried. I hope is possible. But we still want to provide some nice defaults.

I think this we need to discuss internally first. The git repo integration is one that we'll deploy, we can try to see what else can be interesting. For the moment I'm merging this to have already some content up.

**Pull request merged**
